name: Markdown lint

on:
  push:
    branches: [ master ]
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: check-html-links-action step
      id: check-links
      uses: modernweb-dev/check-html-links-action@v1
      with:
        doc-folder: 'html'

